In [1]:
from pathlib import Path

import pandas as pd

In [2]:
ablations = [
    "input_space",
    "masking",
    "augmentation",
    "target_norm",
    "decoders",
    "pos_embed",
    "t_patch_size",
    "flat_baselines",
]

tables = []
for ablation in ablations:
    paths = sorted(Path(f"../{ablation}/output").rglob("eval_table.csv"))
    for path in paths:
        table = pd.read_csv(path)
        table.insert(0, "name", path.parts[-4])
        table.insert(0, "ablation", ablation)
        tables.append(table)

table = pd.concat(tables, ignore_index=True)

print(table.shape)
table.head()

(891, 17)

,ablation,name,model,repr,clf,dataset,epoch,lr,wd,hparam_id,hparam,split,loss,acc,acc_std,f1,f1_std
0,input_space,flat,flat_mae,patch,attn,aabc_sex,3,0.003,0.0050,29,"[3.0, 0.1]",train,0.007031,1.000000,0.000000,1.000000,0.000000
1,input_space,flat,flat_mae,patch,attn,aabc_sex,3,0.003,0.0050,29,"[3.0, 0.1]",validation,0.231261,0.931034,0.033168,0.926768,0.035356
2,input_space,flat,flat_mae,patch,attn,aabc_sex,3,0.003,0.0050,29,"[3.0, 0.1]",test,0.241859,0.890909,0.043995,0.886364,0.046166
3,input_space,flat,flat_mae,patch,linear,aabc_sex,2,0.010,0.0015,35,"[10.0, 0.03]",train,0.218862,0.910828,0.012857,0.908633,0.013220
4,input_space,flat,flat_mae,patch,linear,aabc_sex,2,0.010,0.0015,35,"[10.0, 0.03]",validation,0.309677,0.913793,0.036229,0.905691,0.041216

In [3]:
summary = table.loc[table["split"] == "test"].pivot_table(
    values=["acc", "acc_std"], index=["ablation", "name", "repr", "clf"], columns="dataset"
)
summary.loc[(slice(None), slice(None), "patch", "attn"), :]

                                                   acc                       \
dataset                                       aabc_sex hcpya_rest1lr_gender
ablation       name               repr  clf
augmentation   crop0.5-0.8        patch attn  0.818182             0.778846
               crop0.8-1.0        patch attn  0.836364             0.875000
               jitter0.2          patch attn  0.872727             0.798077
               tr0.8              patch attn  0.890909             0.855769
decoders       attn_reg1          patch attn  0.854545             0.836538
               attn_reg1_pep4     patch attn  0.872727             0.798077
               cross_reg1         patch attn  0.909091             0.826923
               cross_reg1_pep4    patch attn  0.872727             0.807692
               crossreg_reg1      patch attn  0.672727             0.673077
               crossreg_reg16     patch attn  0.854545             0.778846
               crossreg_reg1_pep4 patch attn  0.836364             0.817308
               crossreg_reg4      patch attn  0.890909             0.759615
               crossreg_reg4_pep4 patch attn  0.763636             0.817308
flat_baselines pt-2               patch attn  0.800000             0.798077
               pt-2_bf16          patch attn  0.890909             0.846154
               pt-2_bs64          patch attn  0.909091             0.807692
               pt-2_buf2k         patch attn  0.872727             0.836538
               pt-2_clip0.2       patch attn  0.909091             0.826923
               pt-2_lr2e-3        patch attn  0.909091             0.855769
               pt-2_lr5e-4        patch attn  0.800000             0.846154
               pt-2_mds           patch attn  0.818182             0.865385
               pt-2_noclip        patch attn  0.890909             0.875000
               pt-2_nonorm        patch attn  0.872727             0.826923
               pt-2_simarch       patch attn  0.872727             0.884615
               pt-2_zinit         patch attn  0.872727             0.807692
input_space    flat               patch attn  0.890909             0.894231
               mni_cortex         patch attn  0.862069             0.894231
               schaefer400        patch attn  0.672727             0.730769
masking        tube2x_mr0.5       patch attn  0.945455             0.750000
               tube2x_mr0.75      patch attn  0.800000             0.855769
               tube2x_mr0.9       patch attn  0.890909             0.807692
               tube2x_mr0.95      patch attn  0.818182             0.759615
               tube_mr0.5         patch attn  0.890909             0.817308
               tube_mr0.75        patch attn  0.836364             0.788462
               tube_mr0.9         patch attn  0.890909             0.875000
               tube_mr0.95        patch attn  0.872727             0.778846
               tube_mr0.9_pep4    patch attn  0.872727             0.807692
               tube_mr0.9_pep8    patch attn  0.818182             0.846154
               uniform_mr0.5      patch attn  0.800000             0.750000
               uniform_mr0.75     patch attn  0.890909             0.826923
               uniform_mr0.9      patch attn  0.909091             0.865385
               uniform_mr0.95     patch attn  0.927273             0.788462
pos_embed      abs                patch attn  0.836364             0.836538
               sep                patch attn  0.854545             0.865385
               sincos             patch attn  0.909091             0.817308
t_patch_size   pt-1               patch attn  0.872727             0.865385
               pt-16              patch attn  0.909091             0.778846
               pt-2               patch attn  0.836364             0.846154
               pt-4               patch attn  0.890909             0.807692
               pt-8               patch attn  0.909091             0.769231
target_norm    patch              patch attn  0.909091             0.875000
               pca_nc2            patch attn  0.872727             0.836538
               pca_nc8            patch attn  0.654545             0.615385

                                                                        \
dataset                                      hcpya_task21 nsd_cococlip
ablation       name               repr  clf
augmentation   crop0.5-0.8        patch attn     0.930159     0.224675
               crop0.8-1.0        patch attn     0.985516     0.291466
               jitter0.2          patch attn     0.989286     0.289425
               tr0.8              patch attn     0.990476     0.299629
decoders       attn_reg1          patch attn     0.989683     0.305566
               attn_reg1_pep4     patch attn     0.988492     0.310204
               cross_reg1         patch attn     0.987500     0.285529
               cross_reg1_pep4    patch attn     0.989286     0.324119
               crossreg_reg1      patch attn     0.979167     0.294991
               crossreg_reg16     patch attn     0.982738     0.283117
               crossreg_reg1_pep4 patch attn     0.981746     0.307792
               crossreg_reg4      patch attn     0.984325     0.300000
               crossreg_reg4_pep4 patch attn     0.985119     0.313915
flat_baselines pt-2               patch attn     0.990675     0.312059
               pt-2_bf16          patch attn     0.985516     0.301855
               pt-2_bs64          patch attn     0.989484     0.321336
               pt-2_buf2k         patch attn     0.989683     0.287384
               pt-2_clip0.2       patch attn     0.990278     0.306865
               pt-2_lr2e-3        patch attn     0.987698     0.291651
               pt-2_lr5e-4        patch attn     0.990079     0.318367
               pt-2_mds           patch attn     0.987103     0.291651
               pt-2_noclip        patch attn     0.987897     0.300742
               pt-2_nonorm        patch attn     0.984127     0.296660
               pt-2_simarch       patch attn     0.990476     0.323006
               pt-2_zinit         patch attn     0.988889     0.309647
input_space    flat               patch attn     0.988690     0.303340
               mni_cortex         patch attn     0.969048     0.275510
               schaefer400        patch attn     0.982143     0.272542
masking        tube2x_mr0.5       patch attn     0.978175     0.252690
               tube2x_mr0.75      patch attn     0.988492     0.305937
               tube2x_mr0.9       patch attn     0.984722     0.307236
               tube2x_mr0.95      patch attn     0.979563     0.298887
               tube_mr0.5         patch attn     0.971429     0.249351
               tube_mr0.75        patch attn     0.985516     0.292393
               tube_mr0.9         patch attn     0.990079     0.296475
               tube_mr0.95        patch attn     0.982143     0.301670
               tube_mr0.9_pep4    patch attn     0.985913     0.294249
               tube_mr0.9_pep8    patch attn     0.988690     0.311132
               uniform_mr0.5      patch attn     0.974206     0.253432
               uniform_mr0.75     patch attn     0.986310     0.264564
               uniform_mr0.9      patch attn     0.985913     0.304824
               uniform_mr0.95     patch attn     0.985317     0.291837
pos_embed      abs                patch attn     0.986905     0.314286
               sep                patch attn     0.989683     0.315770
               sincos             patch attn     0.988492     0.313915
t_patch_size   pt-1               patch attn     0.991667     0.327458
               pt-16              patch attn     0.977976     0.266790
               pt-2               patch attn     0.989683     0.310761
               pt-4               patch attn     0.989087     0.300928
               pt-8               patch attn     0.987500     0.275696
target_norm    patch              patch attn     0.987897     0.321707
               pca_nc2            patch attn     0.989484     0.308349
               pca_nc8            patch attn     0.926984     0.192764

                                               acc_std                       \
dataset                                       aabc_sex hcpya_rest1lr_gender
ablation       name               repr  clf
augmentation   crop0.5-0.8        patch attn  0.052632             0.040621
               crop0.8-1.0        patch attn  0.051566             0.032515
               jitter0.2          patch attn  0.048533             0.038786
               tr0.8              patch attn  0.042564             0.032482
decoders       attn_reg1          patch attn  0.049770             0.034154
               attn_reg1_pep4     patch attn  0.048812             0.039264
               cross_reg1         patch attn  0.041525             0.037665
               cross_reg1_pep4    patch attn  0.048082             0.036059
               crossreg_reg1      patch attn  0.063833             0.043970
               crossreg_reg16     patch attn  0.050177             0.038360
               crossreg_reg1_pep4 patch attn  0.047066             0.038036
               crossreg_reg4      patch attn  0.043734             0.041365
               crossreg_reg4_pep4 patch attn  0.055481             0.036261
flat_baselines pt-2               patch attn  0.051266             0.038696
               pt-2_bf16          patch attn  0.043304             0.035267
               pt-2_bs64          patch attn  0.040457             0.037836
               pt-2_buf2k         patch attn  0.046293             0.035299
               pt-2_clip0.2       patch attn  0.040215             0.033653
               pt-2_lr2e-3        patch attn  0.040227             0.033660
               pt-2_lr5e-4        patch attn  0.057823             0.034448
               pt-2_mds           patch attn  0.055761             0.033659
               pt-2_noclip        patch attn  0.043361             0.032987
               pt-2_nonorm        patch attn  0.044387             0.035767
               pt-2_simarch       patch attn  0.046069             0.030799
               pt-2_zinit         patch attn  0.046407             0.037685
input_space    flat               patch attn  0.043995             0.029495
               mni_cortex         patch attn  0.044958             0.030198
               schaefer400        patch attn  0.063378             0.044547
masking        tube2x_mr0.5       patch attn  0.029187             0.042765
               tube2x_mr0.75      patch attn  0.054972             0.034261
               tube2x_mr0.9       patch attn  0.045558             0.041762
               tube2x_mr0.95      patch attn  0.052197             0.044108
               tube_mr0.5         patch attn  0.044006             0.036450
               tube_mr0.75        patch attn  0.049072             0.038273
               tube_mr0.9         patch attn  0.043156             0.031949
               tube_mr0.95        patch attn  0.048533             0.040719
               tube_mr0.9_pep4    patch attn  0.047543             0.036263
               tube_mr0.9_pep8    patch attn  0.055546             0.035179
               uniform_mr0.5      patch attn  0.055103             0.043014
               uniform_mr0.75     patch attn  0.043991             0.035733
               uniform_mr0.9      patch attn  0.040481             0.032487
               uniform_mr0.95     patch attn  0.035152             0.039584
pos_embed      abs                patch attn  0.050013             0.035516
               sep                patch attn  0.049485             0.032528
               sincos             patch attn  0.041048             0.036859
t_patch_size   pt-1               patch attn  0.045286             0.032971
               pt-16              patch attn  0.042139             0.039549
               pt-2               patch attn  0.052045             0.035538
               pt-4               patch attn  0.043670             0.035069
               pt-8               patch attn  0.040670             0.039712
target_norm    patch              patch attn  0.036860             0.031715
               pca_nc2            patch attn  0.046382             0.035646
               pca_nc8            patch attn  0.056993             0.046413


dataset                                      hcpya_task21 nsd_cococlip
ablation       name               repr  clf
augmentation   crop0.5-0.8        patch attn     0.003538     0.005168
               crop0.8-1.0        patch attn     0.001575     0.005637
               jitter0.2          patch attn     0.001357     0.005537
               tr0.8              patch attn     0.001391     0.005584
decoders       attn_reg1          patch attn     0.001413     0.005290
               attn_reg1_pep4     patch attn     0.001447     0.005217
               cross_reg1         patch attn     0.001519     0.005301
               cross_reg1_pep4    patch attn     0.001455     0.005532
               crossreg_reg1      patch attn     0.001993     0.005310
               crossreg_reg16     patch attn     0.001831     0.005121
               crossreg_reg1_pep4 patch attn     0.001894     0.005638
               crossreg_reg4      patch attn     0.001688     0.005350
               crossreg_reg4_pep4 patch attn     0.001675     0.005353
flat_baselines pt-2               patch attn     0.001293     0.005542
               pt-2_bf16          patch attn     0.001653     0.005385
               pt-2_bs64          patch attn     0.001442     0.005340
               pt-2_buf2k         patch attn     0.001447     0.005545
               pt-2_clip0.2       patch attn     0.001340     0.005568
               pt-2_lr2e-3        patch attn     0.001532     0.005497
               pt-2_lr5e-4        patch attn     0.001309     0.005463
               pt-2_mds           patch attn     0.001549     0.005406
               pt-2_noclip        patch attn     0.001453     0.005784
               pt-2_nonorm        patch attn     0.001634     0.005261
               pt-2_simarch       patch attn     0.001323     0.005790
               pt-2_zinit         patch attn     0.001500     0.005445
input_space    flat               patch attn     0.001454     0.005370
               mni_cortex         patch attn     0.002525     0.005255
               schaefer400        patch attn     0.001845     0.005303
masking        tube2x_mr0.5       patch attn     0.002034     0.005044
               tube2x_mr0.75      patch attn     0.001487     0.005645
               tube2x_mr0.9       patch attn     0.001659     0.005588
               tube2x_mr0.95      patch attn     0.001943     0.005289
               tube_mr0.5         patch attn     0.002321     0.005152
               tube_mr0.75        patch attn     0.001699     0.005239
               tube_mr0.9         patch attn     0.001369     0.005305
               tube_mr0.95        patch attn     0.001865     0.005099
               tube_mr0.9_pep4    patch attn     0.001650     0.005601
               tube_mr0.9_pep8    patch attn     0.001376     0.005323
               uniform_mr0.5      patch attn     0.002330     0.004922
               uniform_mr0.75     patch attn     0.001607     0.005268
               uniform_mr0.9      patch attn     0.001583     0.005585
               uniform_mr0.95     patch attn     0.001621     0.005199
pos_embed      abs                patch attn     0.001605     0.005554
               sep                patch attn     0.001414     0.005282
               sincos             patch attn     0.001426     0.005382
t_patch_size   pt-1               patch attn     0.001272     0.005674
               pt-16              patch attn     0.002092     0.005439
               pt-2               patch attn     0.001367     0.005649
               pt-4               patch attn     0.001447     0.005256
               pt-8               patch attn     0.001532     0.005185
target_norm    patch              patch attn     0.001472     0.005489
               pca_nc2            patch attn     0.001434     0.005321
               pca_nc8            patch attn     0.003576     0.004776

In [4]:
summary.loc[(slice(None), slice(None), "reg", slice(None)), :]

                                              acc                       \
dataset                                  aabc_sex hcpya_rest1lr_gender
ablation name               repr clf
decoders attn_reg1          reg  linear  0.872727             0.807692
         attn_reg1_pep4     reg  linear  0.890909             0.846154
         cross_reg1         reg  linear  0.890909             0.769231
         cross_reg1_pep4    reg  linear  0.909091             0.788462
         crossreg_reg1      reg  linear  0.781818             0.605769
         crossreg_reg16     reg  attn    0.909091             0.788462
                                 linear  0.890909             0.759615
         crossreg_reg1_pep4 reg  linear  0.872727             0.711538
         crossreg_reg4      reg  attn    0.800000             0.778846
                                 linear  0.945455             0.769231
         crossreg_reg4_pep4 reg  linear  0.909091             0.817308

                                                                    acc_std  \
dataset                                 hcpya_task21 nsd_cococlip  aabc_sex
ablation name               repr clf
decoders attn_reg1          reg  linear     0.959127     0.117811  0.047458
         attn_reg1_pep4     reg  linear     0.952579     0.106865  0.044098
         cross_reg1         reg  linear     0.914484     0.080334  0.043283
         cross_reg1_pep4    reg  linear     0.893254     0.095362  0.041413
         crossreg_reg1      reg  linear     0.974206     0.244156  0.056361
         crossreg_reg16     reg  attn       0.976786     0.305380  0.038779
                                 linear     0.958135     0.105937  0.044098
         crossreg_reg1_pep4 reg  linear     0.976190     0.245640  0.047083
         crossreg_reg4      reg  attn       0.978571     0.274768  0.053266
                                 linear     0.962500     0.132653  0.031540
         crossreg_reg4_pep4 reg  linear     0.978373     0.205195  0.038779

                                                                           \
dataset                                 hcpya_rest1lr_gender hcpya_task21
ablation name               repr clf
decoders attn_reg1          reg  linear             0.035640     0.002989
         attn_reg1_pep4     reg  linear             0.034334     0.002879
         cross_reg1         reg  linear             0.039071     0.003750
         cross_reg1_pep4    reg  linear             0.038961     0.004220
         crossreg_reg1      reg  linear             0.048078     0.002356
         crossreg_reg16     reg  attn               0.038265     0.002112
                                 linear             0.038261     0.002731
         crossreg_reg1_pep4 reg  linear             0.043671     0.002087
         crossreg_reg4      reg  attn               0.038708     0.002005
                                 linear             0.038820     0.002611
         crossreg_reg4_pep4 reg  linear             0.035060     0.002076


dataset                                 nsd_cococlip
ablation name               repr clf
decoders attn_reg1          reg  linear     0.003619
         attn_reg1_pep4     reg  linear     0.003599
         cross_reg1         reg  linear     0.003257
         cross_reg1_pep4    reg  linear     0.003694
         crossreg_reg1      reg  linear     0.005134
         crossreg_reg16     reg  attn       0.005261
                                 linear     0.003813
         crossreg_reg1_pep4 reg  linear     0.004999
         crossreg_reg4      reg  attn       0.005085
                                 linear     0.003871
         crossreg_reg4_pep4 reg  linear     0.004519

In [5]:
baseline = summary.loc[("input_space", "flat", "patch", "attn")]
baseline

         dataset
acc      aabc_sex                0.890909
         hcpya_rest1lr_gender    0.894231
         hcpya_task21            0.988690
         nsd_cococlip            0.303340
acc_std  aabc_sex                0.043995
         hcpya_rest1lr_gender    0.029495
         hcpya_task21            0.001454
         nsd_cococlip            0.005370
Name: (input_space, flat, patch, attn), dtype: float64

In [9]:
ref_acc = baseline[("acc", "nsd_cococlip")]
ref_std = baseline[("acc_std", "nsd_cococlip")]
threshold = 3


def format_acc(acc):
    if pd.isna(acc):
        return "—"
    s = f"{acc * 100:.1f}"
    if acc > ref_acc + threshold * ref_std:
        s = r"\textbf{" + s + r"}"
    elif acc < ref_acc - threshold * ref_std:
        s = r"\badc{" + s + r"}"
    if acc == ref_acc:
        s = r"\gc{" + s + r"}"
    return s


print(f"{ref_acc:.4f} {ref_std:.4f}")

0.3033 0.0054

In [7]:
# masking table
masking_summary = summary.loc[("masking", slice(None), "patch", "attn")]
masking_summary

                      acc                                                 \
dataset          aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
tube2x_mr0.5     0.945455             0.750000     0.978175     0.252690
tube2x_mr0.75    0.800000             0.855769     0.988492     0.305937
tube2x_mr0.9     0.890909             0.807692     0.984722     0.307236
tube2x_mr0.95    0.818182             0.759615     0.979563     0.298887
tube_mr0.5       0.890909             0.817308     0.971429     0.249351
tube_mr0.75      0.836364             0.788462     0.985516     0.292393
tube_mr0.9       0.890909             0.875000     0.990079     0.296475
tube_mr0.95      0.872727             0.778846     0.982143     0.301670
tube_mr0.9_pep4  0.872727             0.807692     0.985913     0.294249
tube_mr0.9_pep8  0.818182             0.846154     0.988690     0.311132
uniform_mr0.5    0.800000             0.750000     0.974206     0.253432
uniform_mr0.75   0.890909             0.826923     0.986310     0.264564
uniform_mr0.9    0.909091             0.865385     0.985913     0.304824
uniform_mr0.95   0.927273             0.788462     0.985317     0.291837

                  acc_std
dataset          aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
tube2x_mr0.5     0.029187             0.042765     0.002034     0.005044
tube2x_mr0.75    0.054972             0.034261     0.001487     0.005645
tube2x_mr0.9     0.045558             0.041762     0.001659     0.005588
tube2x_mr0.95    0.052197             0.044108     0.001943     0.005289
tube_mr0.5       0.044006             0.036450     0.002321     0.005152
tube_mr0.75      0.049072             0.038273     0.001699     0.005239
tube_mr0.9       0.043156             0.031949     0.001369     0.005305
tube_mr0.95      0.048533             0.040719     0.001865     0.005099
tube_mr0.9_pep4  0.047543             0.036263     0.001650     0.005601
tube_mr0.9_pep8  0.055546             0.035179     0.001376     0.005323
uniform_mr0.5    0.055103             0.043014     0.002330     0.004922
uniform_mr0.75   0.043991             0.035733     0.001607     0.005268
uniform_mr0.9    0.040481             0.032487     0.001583     0.005585
uniform_mr0.95   0.035152             0.039584     0.001621     0.005199

In [8]:
# strategy x ratio grid
mask_ratios = [0.5, 0.75, 0.9, 0.95]
strategies = ["uniform", "tube", "tube2x"]

names = {"tube2x": r"tube (2\x)"}

records = []
for strategy in strategies:
    record = {"strategy": names.get(strategy, strategy)}
    for ratio in mask_ratios:
        label = f"{100 * ratio:.0f}"
        key = f"{strategy}_mr{ratio}"
        try:
            acc = masking_summary.loc[key, ("acc", "nsd_cococlip")]
            record[label] = format_acc(acc)
        except KeyError:
            record[label] = "-"

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{lllll}
\toprule
strategy & 50 & 75 & 90 & 95 \\
\midrule
uniform & \badc{25.3} & \badc{26.5} & 30.5 & 29.2 \\
tube & \badc{24.9} & 29.2 & 29.6 & 30.2 \\
tube (2\x) & \badc{25.3} & 30.6 & 30.7 & 29.9 \\
\bottomrule
\end{tabular}

In [9]:
# augmentation
aug_summary = summary.loc[("augmentation", slice(None), "patch", "attn")]
aug_summary

                  acc                                                 \
dataset      aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
crop0.5-0.8  0.818182             0.778846     0.930159     0.224675
crop0.8-1.0  0.836364             0.875000     0.985516     0.291466
jitter0.2    0.872727             0.798077     0.989286     0.289425
tr0.8        0.890909             0.855769     0.990476     0.299629

              acc_std
dataset      aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
crop0.5-0.8  0.052632             0.040621     0.003538     0.005168
crop0.8-1.0  0.051566             0.032515     0.001575     0.005637
jitter0.2    0.048533             0.038786     0.001357     0.005537
tr0.8        0.042564             0.032482     0.001391     0.005584

In [10]:
# single column
names = {
    "tr0.8": "TR jit",
    "jitter0.2": "gray jit",
    "crop0.8-1.0": "crop (weak)",
    "crop0.5-0.8": "crop (strong)",
}

records = [
    {
        "case": "none",
        "acc": format_acc(baseline[("acc", "nsd_cococlip")]),
    }
]

for key, name in names.items():
    record = {
        "case": name,
        "acc": format_acc(aug_summary.loc[key, ("acc", "nsd_cococlip")]),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{ll}
\toprule
case & acc \\
\midrule
none & \gc{30.3} \\
TR jit & 30.0 \\
gray jit & 28.9 \\
crop (weak) & 29.1 \\
crop (strong) & \badc{22.5} \\
\bottomrule
\end{tabular}

In [11]:
# target norm
target_summary = summary.loc[("target_norm", slice(None), "patch", "attn")]
target_summary

              acc                                                  acc_std  \
dataset  aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip  aabc_sex
name
patch    0.909091             0.875000     0.987897     0.321707  0.036860
pca_nc2  0.872727             0.836538     0.989484     0.308349  0.046382
pca_nc8  0.654545             0.615385     0.926984     0.192764  0.056993


dataset hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
patch               0.031715     0.001472     0.005489
pca_nc2             0.035646     0.001434     0.005321
pca_nc8             0.046413     0.003576     0.004776

In [12]:
names = {
    "patch": "pix norm",
    "pca_nc2": "pix $-$ pca ($d$=2)",
    "pca_nc8": "pix $-$ pca ($d$=8)",
}

records = [
    {
        "case": "none",
        "acc": format_acc(baseline[("acc", "nsd_cococlip")]),
    }
]

for key, name in names.items():
    record = {
        "case": name,
        "acc": format_acc(target_summary.loc[key, ("acc", "nsd_cococlip")]),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{ll}
\toprule
case & acc \\
\midrule
none & \gc{30.3} \\
pix norm & \textbf{32.2} \\
pix $-$ pca ($d$=2) & 30.8 \\
pix $-$ pca ($d$=8) & \badc{19.3} \\
\bottomrule
\end{tabular}

In [13]:
# t patch size
pt_summary = summary.loc[("t_patch_size", slice(None), "patch", "attn")]
pt_summary

              acc                                                  acc_std  \
dataset  aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip  aabc_sex
name
pt-1     0.872727             0.865385     0.991667     0.327458  0.045286
pt-16    0.909091             0.778846     0.977976     0.266790  0.042139
pt-2     0.836364             0.846154     0.989683     0.310761  0.052045
pt-4     0.890909             0.807692     0.989087     0.300928  0.043670
pt-8     0.909091             0.769231     0.987500     0.275696  0.040670


dataset hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
pt-1                0.032971     0.001272     0.005674
pt-16               0.039549     0.002092     0.005439
pt-2                0.035538     0.001367     0.005649
pt-4                0.035069     0.001447     0.005256
pt-8                0.039712     0.001532     0.005185

In [14]:
patches_per_frame = 364  # fixed num patches per flat map

names = {
    "pt-16": "16",
    "pt-8": "8",
    "pt-4": "4",
    "pt-2": "2",
    "pt-1": "1",
}

records = []
for key, name in names.items():
    record = {
        "$p_t$": name,
        "patches": int(patches_per_frame * 16 / int(name)),
        "acc": format_acc(pt_summary.loc[key, ("acc", "nsd_cococlip")]),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{lrl}
\toprule
$p_t$ & patches & acc \\
\midrule
16 & 364 & \badc{26.7} \\
8 & 728 & \badc{27.6} \\
4 & 1456 & 30.1 \\
2 & 2912 & 31.1 \\
1 & 5824 & \textbf{32.7} \\
\bottomrule
\end{tabular}

In [15]:
pos_summary = summary.loc[("pos_embed", slice(None), "patch", "attn")]
pos_summary

              acc                                                  acc_std  \
dataset  aabc_sex hcpya_rest1lr_gender hcpya_task21 nsd_cococlip  aabc_sex
name
abs      0.836364             0.836538     0.986905     0.314286  0.050013
sep      0.854545             0.865385     0.989683     0.315770  0.049485
sincos   0.909091             0.817308     0.988492     0.313915  0.041048


dataset hcpya_rest1lr_gender hcpya_task21 nsd_cococlip
name
abs                 0.035516     0.001605     0.005554
sep                 0.032528     0.001414     0.005282
sincos              0.036859     0.001426     0.005382

In [16]:
names = {
    "sep": "sep",
    "abs": "abs",
    "sincos": "sincos",
}

records = []
for key, name in names.items():
    record = {
        "case": name,
        "acc": format_acc(pos_summary.loc[key, ("acc", "nsd_cococlip")]),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{ll}
\toprule
case & acc \\
\midrule
sep & 31.6 \\
abs & 31.4 \\
sincos & 31.4 \\
\bottomrule
\end{tabular}

In [17]:
decoder_summary = summary.loc[("decoders", slice(None))]
decoder_summary

                                      acc                                    \
dataset                          aabc_sex hcpya_rest1lr_gender hcpya_task21
name               repr  clf
attn_reg1          patch attn    0.854545             0.836538     0.989683
                   reg   linear  0.872727             0.807692     0.959127
attn_reg1_pep4     patch attn    0.872727             0.798077     0.988492
                   reg   linear  0.890909             0.846154     0.952579
cross_reg1         patch attn    0.909091             0.826923     0.987500
                   reg   linear  0.890909             0.769231     0.914484
cross_reg1_pep4    patch attn    0.872727             0.807692     0.989286
                   reg   linear  0.909091             0.788462     0.893254
crossreg_reg1      patch attn    0.672727             0.673077     0.979167
                   reg   linear  0.781818             0.605769     0.974206
crossreg_reg16     patch attn    0.854545             0.778846     0.982738
                   reg   attn    0.909091             0.788462     0.976786
                         linear  0.890909             0.759615     0.958135
crossreg_reg1_pep4 patch attn    0.836364             0.817308     0.981746
                   reg   linear  0.872727             0.711538     0.976190
crossreg_reg4      patch attn    0.890909             0.759615     0.984325
                   reg   attn    0.800000             0.778846     0.978571
                         linear  0.945455             0.769231     0.962500
crossreg_reg4_pep4 patch attn    0.763636             0.817308     0.985119
                   reg   linear  0.909091             0.817308     0.978373

                                               acc_std                       \
dataset                         nsd_cococlip  aabc_sex hcpya_rest1lr_gender
name               repr  clf
attn_reg1          patch attn       0.305566  0.049770             0.034154
                   reg   linear     0.117811  0.047458             0.035640
attn_reg1_pep4     patch attn       0.310204  0.048812             0.039264
                   reg   linear     0.106865  0.044098             0.034334
cross_reg1         patch attn       0.285529  0.041525             0.037665
                   reg   linear     0.080334  0.043283             0.039071
cross_reg1_pep4    patch attn       0.324119  0.048082             0.036059
                   reg   linear     0.095362  0.041413             0.038961
crossreg_reg1      patch attn       0.294991  0.063833             0.043970
                   reg   linear     0.244156  0.056361             0.048078
crossreg_reg16     patch attn       0.283117  0.050177             0.038360
                   reg   attn       0.305380  0.038779             0.038265
                         linear     0.105937  0.044098             0.038261
crossreg_reg1_pep4 patch attn       0.307792  0.047066             0.038036
                   reg   linear     0.245640  0.047083             0.043671
crossreg_reg4      patch attn       0.300000  0.043734             0.041365
                   reg   attn       0.274768  0.053266             0.038708
                         linear     0.132653  0.031540             0.038820
crossreg_reg4_pep4 patch attn       0.313915  0.055481             0.036261
                   reg   linear     0.205195  0.038779             0.035060


dataset                         hcpya_task21 nsd_cococlip
name               repr  clf
attn_reg1          patch attn       0.001413     0.005290
                   reg   linear     0.002989     0.003619
attn_reg1_pep4     patch attn       0.001447     0.005217
                   reg   linear     0.002879     0.003599
cross_reg1         patch attn       0.001519     0.005301
                   reg   linear     0.003750     0.003257
cross_reg1_pep4    patch attn       0.001455     0.005532
                   reg   linear     0.004220     0.003694
crossreg_reg1      patch attn       0.001993     0.005310
                   reg   linear     0.002356     0.005134
crossreg_reg16     patch attn       0.001831     0.005121
                   reg   attn       0.002112     0.005261
                         linear     0.002731     0.003813
crossreg_reg1_pep4 patch attn       0.001894     0.005638
                   reg   linear     0.002087     0.004999
crossreg_reg4      patch attn       0.001688     0.005350
                   reg   attn       0.002005     0.005085
                         linear     0.002611     0.003871
crossreg_reg4_pep4 patch attn       0.001675     0.005353
                   reg   linear     0.002076     0.004519

In [18]:
def format_acc2(acc):
    if pd.isna(acc):
        return "—"
    s = f"{acc * 100:.1f}"
    if acc > ref_acc + threshold * ref_std:
        s = r"\textbf{" + s + r"}"
    return s

In [19]:
# decoding strategy x attn linear
names = {
    "attn_reg1": "self",
    "cross_reg1": "cross",
    "crossreg_reg16": "cross-reg (16)",
    "crossreg_reg4": "cross-reg (4)",
    "crossreg_reg1": "cross-reg (1)",
}

records = []

for key, name in names.items():
    record = {
        "decoder": name,
        "attn": format_acc2(decoder_summary.loc[(key, "patch", "attn"), ("acc", "nsd_cococlip")]),
        "lin": format_acc2(decoder_summary.loc[(key, "reg", "linear"), ("acc", "nsd_cococlip")]),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{lll}
\toprule
decoder & attn & lin \\
\midrule
self & 30.6 & 11.8 \\
cross & 28.6 & 8.0 \\
cross-reg (16) & 28.3 & 10.6 \\
cross-reg (4) & 30.0 & 13.3 \\
cross-reg (1) & 29.5 & 24.4 \\
\bottomrule
\end{tabular}

In [21]:
# decoding strategy x with / without decoder masking
names = {
    "attn_reg1": "self",
    "cross_reg1": "cross",
    "crossreg_reg4": "cross-reg (4)",
    "crossreg_reg1": "cross-reg (1)",
}

records = []

for key, name in names.items():
    record = {
        "decoder": name,
        "w/o edge mask": format_acc2(
            decoder_summary.loc[(key, "patch", "attn"), ("acc", "nsd_cococlip")]
        ),
        "w/ edge mask": format_acc2(
            decoder_summary.loc[(f"{key}_pep4", "patch", "attn"), ("acc", "nsd_cococlip")]
        ),
    }

    records.append(record)

df = pd.DataFrame.from_records(records)
print(df.to_latex(index=False))

\begin{tabular}{lll}
\toprule
decoder & w/o edge mask & w/ edge mask \\
\midrule
self & 30.6 & 31.0 \\
cross & 28.6 & \textbf{32.4} \\
cross-reg (4) & 30.0 & 31.4 \\
cross-reg (1) & 29.5 & 30.8 \\
\bottomrule
\end{tabular}